### PR TITLE
Fix interface filtering and add more patterns

### LINKED ISSUE #15: Issue with "lo" is being matched for "wlo1"
After an update, the interface  "lo" being matched for "wlo1"  which has made the extension stop working.

Here's the content of `/proc/net/dev`
```
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo: 1168853    2021    0    0    0     0          0         0  1168853    2021    0    0    0     0       0          0
enp3s0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  wlo1: 3490410817 2723379    0    0    0     0          0         0 56827636  301137    0    0    0     0       0          0
virbr0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr1:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
docker0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr2:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
```

### PR DESCRIPTION
**Pull request by ShrirajHegde**
Exactly match the interface "lo".
Filter docker interfaces.

Fixes #15 introduced by c4fec82ada236e65d4aed6bd27cfd99edd4a31bb

### CODE REVIEW

**Comment by AlShakib** [comment]
Thank you for your pull request. It's already fixed! 😋
Currently under review on Gnome Extensions.

**Comment by ShrirajHegde** [comment]
Ah ! It was fixed before opened pull request.

What do you think about positively matching only for Wi-Fi and Ethernet interfaces?

```js
    if (
      column[0].match(/^wlo/) ||
      column[0].match(/^wlan/) ||
      column[0].match(/^enp/)
    ) 
```

**Comment by ShrirajHegde** [comment]
Also, @AlShakib could you exclude docker interfaces if not planning on matching positively?

**Comment by AlShakib** [comment]
It could be nice but there is no guarantee that the ethernet interface will always start with `enp`. It could be `eno` or `ens` or something complex like `enx78e7d1ea46da`. Same goes for wifi as well. So it'll be much harder to ensure positive matching.

**Pull request closed without merging**
